name: Publish Packages

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'src/Spoleto.FastPayments.AlfaBank.Tests/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/Spoleto.FastPayments.AlfaBank/Spoleto.FastPayments.AlfaBank.csproj
    - name: Build
      run: dotnet build src/Spoleto.FastPayments.AlfaBank/Spoleto.FastPayments.AlfaBank.csproj --configuration Release --no-restore
    - name: Publish to Nuget
      uses: alirezanet/publish-nuget@v3.0.4
      with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: src/Spoleto.FastPayments.AlfaBank/Spoleto.FastPayments.AlfaBank.csproj
          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          INCLUDE_SYMBOLS: true
          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: false
